# This file was generated by GoReleaser. DO NOT EDIT.
class Goad < Formula
  desc ""
  homepage ""
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hmschreck/goad/releases/download/0.1.5/goad_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "41851d2764db1c210c321cb9767e4afd4a20ce1599a622da048a6f533a42e6df"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hmschreck/goad/releases/download/0.1.5/goad_0.1.5_Linux_x86_64.tar.gz"
      sha256 "8940d2be8156b82c8992d8dfafc4b248c25525c1947039010c5b6ff44c8fc251"
    end
  end

  def install
    bin.install "goad"
  end
end
