# This file was generated by GoReleaser. DO NOT EDIT.
class Goad < Formula
  desc ""
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hmschreck/goad/releases/download/0.2.0/goad_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "c4c79274e09c9ff8f5e61e3ca601ba0c64d124385dadd0693541a0bcc9b75130"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hmschreck/goad/releases/download/0.2.0/goad_0.2.0_Linux_x86_64.tar.gz"
      sha256 "2fef65f051b3efc8c4357eea72aa287251267848314a9d21b11abcda9faf4551"
    end
  end

  def install
    bin.install "goad"
  end
end
